name: Lint Java Backend

on:
  push:
  pull_request:

jobs:
  lint-java:
    runs-on: ubuntu-latest
    name: Compile & Checkstyle Java Backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java backend
        run: ./mvnw clean compile || mvn clean compile

      - name: Download Checkstyle
        run: curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.1/checkstyle-10.12.1-all.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c /google_checks.xml app/src/main/java/com/project/back_end || true
